apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: multicluster-engine
namePrefix: mce-

resources:
- default/

## Patch the default resources with OCP downstream requirements.
patches:
  - target:
      kind: Namespace
    patch: |-
      $patch: delete
      apiVersion: v1
      kind: Namespace
      metadata:
        name: capm3-system
  - target:
      version: v1
      kind: Certificate
      name: capm3-serving-cert
    patch: |-
      - op: replace
        path: /spec/commonName
        value: "mce-capm3-webhook-service.multicluster-engine.svc"
      - op: replace
        path: /spec/dnsNames/0
        value: "mce-capm3-webhook-service.multicluster-engine.svc"
      - op: replace
        path: /spec/dnsNames/1
        value: "mce-capm3-webhook-service.multicluster-engine.svc.cluster.local"
  # Replace Deployment with default values & helm chart value
  - target:
      version: v1
      kind: CustomResourceDefinition
      annotationSelector: cert-manager.io/inject-ca-from
    patch: |-
      - op: replace
        path: /metadata/annotations/cert-manager.io~1inject-ca-from
        value: "multicluster-engine/mce-capm3-serving-cert"
  - target:
      version: v1
      kind: Deployment
      name: capm3-controller-manager
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: '{{ .Values.manager.image.url }}:{{ .Values.manager.image.tag }}'
      - op: replace
        path: /spec/template/spec/containers/0/args/1
        value: --enableBMHNameBasedPreallocation=false
      - op: replace
        path: /spec/template/spec/containers/0/args/2
        value: --diagnostics-address=:8443
      - op: replace
        path: /spec/template/spec/containers/0/args/3
        value: --insecure-diagnostics=false
      - op: replace
        path: /spec/template/spec/containers/0/args/4
        value: --tls-min-version=VersionTLS13
      - op: replace
        path: /spec/template/spec/securityContext/runAsUser
        value: 65532
      - op: replace
        path: /spec/template/spec/securityContext/runAsGroup
        value: 65532
  - target:
      version: v1
      kind: MutatingWebhookConfiguration
      name: capm3-mutating-webhook-configuration
    patch: |-
      - op: replace
        path: /metadata/annotations/cert-manager.io~1inject-ca-from
        value: "multicluster-engine/mce-capm3-serving-cert"
  - target:
      version: v1
      kind: ValidatingWebhookConfiguration
      name: capm3-validating-webhook-configuration
    patch: |-
      - op: replace
        path: /metadata/annotations/cert-manager.io~1inject-ca-from
        value: "multicluster-engine/mce-capm3-serving-cert"
